apiVersion: v1
kind: Secret
metadata:
  name: finalproject-secrets
  namespace: finalproject
type: Opaque
# NOTE: Values are base64-encoded; replace with your own secrets
data:
  # example: echo -n "supersecret" | base64 => c3VwZXJzZWNyZXQ=
  DB_PASSWORD: c3VwZXJzZWNyZXQ=
  API_KEY: YXBpX2tleV9leGFtcGxl