apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: finalproject-hpa
  namespace: finalproject
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: finalproject-app
  minReplicas: 2
  maxReplicas: 10
  targetCPUUtilizationPercentage: 50